name: Run Pytest on PRs

on:
  pull_request:
    branches:
      - "**" # Run on all branches when a PR is opened or updated

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 # Specify the Python version you use

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Or use `pip install .` if using pyproject.toml

      # Run pytest
      - name: Run tests with pytest
        run: |
          pytest --maxfail=5 --disable-warnings -v
